### ISSUE TITLE
Not working on latest Windows 11 canary

### ISSUE THREAD

**Issue by gailium119** [6ziv/CustomUAC#1]
In latest canary builds, Microsoft changed the size of the UAC data.
Supposingly the code should be changed to something like that:
```cpp
       write_target = *reinterpret_cast<void**>(buffer + 0xC0);// Original: 6 * sizeof(UINT32) + 4 * sizeof(void*));
	size_t base_offset = 0;
	if (uac_type == 0 || uac_type ==2) {//Known to be excutable
	//uac_type==2 means msi. which is similar to exe except that content meanings have changed.
		base_offset = 0xD0;//Original:6 * sizeof(DWORD) + 6 * sizeof(void*);
	}
	else if (uac_type == 1) {//dll
		base_offset = 0xC8;//Original:6 * sizeof(DWORD) + 5 * sizeof(void*);
	}`

**Comment by 6ziv** [comment]
Sorry for the really late reply. Haven't checked email for a while.
Seems the added data is a base64-ed guid, but still not sure why it is serialized into such a long buffer, or how it should be used.
I managed to tell the new data from the old, but not fully tested, so I put the fixup code in a new branch.
Thanks a lot for the helpful information.
